[package]
name = "day08"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
regex = "1.10.2"
num-integer = "0.1"
itertools = "0.13.0"
