[package]
name = "puzzle20"
authors.workspace = true
description.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
base64 = "0.22.1"
itertools = "0.14.0"

[lints]
workspace = true
