[package]
name = "puzzle10"
authors.workspace = true
description.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bcrypt = "0.17.0"
fxhash = "0.2.1"
itertools = "0.14.0"
unicode-normalization = "0.1.24"

[lints]
workspace = true
