[package]
name = "day22"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
mod_exp = "1.0.1"
modinverse = "0.1.1"
num = "0.4.1"
