[workspace]
resolver = "2"

members = [
    "day01",
    "day02",
    "day03",
    "day04",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Vincent Oberle"]
description = "Advent of Code 2015"
