[package]
name = "day10"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
advent-of-code-ocr = "0.1.1"
