[package]
name = "puzzle15"
authors.workspace = true
description.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
chrono = "0.4.40"
chrono-tz = "0.10.3"
itertools = "0.14.0"

[lints]
workspace = true
