[package]
name = "day25"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
intcode = { path = "../intcode" }
itertools = "0.12.1"
