[package]
name = "day09"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
dlv-list = "0.5.2"
regex = "1.10.3"
