[package]
name = "day13"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
advent-of-code-ocr = "0.1.1"
fxhash = "0.2.1"
itertools = "0.12.1"
