[package]
name = "day18"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.0"
