[package]
name = "day24"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
itertools = "0.12.1"
lazy_static = "1.4.0"
regex = "1.10.3"
