[package]
name = "puzzle12"
authors.workspace = true
description.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
deunicode = "1.6.1"
itertools = "0.14.0"

[lints]
workspace = true
