[package]
name = "day12"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
fxhash = "0.2.1"
num-integer = "0.1.46"
regex = "1.10.3"
