[package]
name = "day25"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
fxhash = "0.2.1"
itertools = "0.12.0"
regex = "1.10.3"
