[package]
name = "day04"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
md5 = "0.7.0"
rayon = "1.8.0"
