[package]
name = "utils"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Oberle"]
description = "Advent of Code utils"

[lints.clippy]
pedantic = "deny"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
fxhash = "0.2.1"
md5 = "0.7.0"
