[package]
name = "day09"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[features]
previous_days = []

[dependencies]
itertools = "0.12.1"
