[package]
name = "day23"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
itertools = "0.12.1"
regex = "1.10.3"
