#!/bin/bash

CDIR=$( dirname "$0" )
echo 2015: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2015/README.md | wc -m) 🌟
echo 2016: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2016/README.md | wc -m) 🌟
echo 2017: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2017/README.md | wc -m) 🌟
echo 2018: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2018/README.md | wc -m) 🌟
echo 2019: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2019/README.md | wc -m) 🌟
echo 2020: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2020/README.md | wc -m) 🌟
echo 2021: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2021/README.md | wc -m) 🌟
echo 2022: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2022/README.md | wc -m) 🌟
echo 2023: $(tr -d -c '🌟' 2>/dev/null < $CDIR/../2023/README.md | wc -m) 🌟

echo See your calendars with "aoc calendar -y YYYY"
