[package]
name = "day17"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
fxhash = "0.2.1"

[features]
my_debug = []
